include:
  - project: 'medrest/devops/hiraishin'
    ref: v0
    file: 'pipelines/.gitlab-ci-pipeline.yml'
  - template: Security/SAST.gitlab-ci.yml

# Define Global Variables
variables:
  # Variable for override Project Name Identity
  SERVICE_CODE_NAME: "${CI_PROJECT_NAME}"
  # Pipelines Toggle Variables
  SERVICE_TEST_ENABLED: ""
  # Service Build toggle variable
  BUILD_SERVICE_ENABLED: "docker"

sast:
  stage: test