apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-app.fullname" . }}
  labels:
    {{- include "weather-app.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports: 
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.portNumber }}
      protocol: {{ .Values.service.portProtocol }}
      targetPort: {{ .Values.service.portNumber }}
  selector:
    {{- include "weather-app.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
